branch-defaults:
  default:
    environment: aws-cloud-developer-2-Fullstack-apps-dev
global:
  application_name: aws-cloud-developer-2-Fullstack-apps
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 20 running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
